### ISSUE TITLE
Location of archives?

### ISSUE THREAD

**Issue by DanielHeilmeier** [iswunistuttgart/latex-templates#8]
Hello,

from the README: "If you download the files from the respective released archives (article, book, or thesis) [...]" I was wondering where I can find these archives. I would like to start writing my thesis but the only hint of a .tex file is to be found in one of the forks and that doesn't compile for me although I have installed both TeXlive and luaLaTeX. I would appreciate a nudge in the right direction.

Greetings,
Daniel

**Comment by philipptempel** [comment]
Please see https://gitlab.com/philipptempel/ustutt-latex-templates as this is a disconnected mirror of the private repo at ISW.
Since I have left ISW in September 2019, no one has taken care of keeping the sync between git.isw.uni-stuttgart.de and github.com alive. I still need to link my CI artifacts with releases on my repo, but you can download the most recent version from https://gitlab.com/philipptempel/ustutt-latex-templates/-/jobs/artifacts/master/download?job=dist

**Comment by chhinze** [comment]
The last version here is 1.3.1 (2 June 2020), so there *were* update after September 2019. 
The credentials for uploading the artifacts don't work anymore, that's why the CI pipeline fails. Any clue @philipptempel?

**Comment by philipptempel** [comment]
Affirmative. Till then, my personal GH access token were set up for repo mirroring and the `ship` job in the CI. However, these have expired some time around beginning of June and I have no intentions of extending them since these are personal access tokens i.e., not bound to a repo but to my GH user.

**Comment by DanielHeilmeier** [comment]
I see. Thank you for your effort! I will try it with your links. Greetings
